---
- name: Download script and run (Centos and RedOS) 
  block:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Download script
      get_url:
        url: "{{ url_cs_redhat }}"
        dest: /tmp/install-RedHat.sh
        mode: '0644'
        validate_certs: no
        force: yes
    - name: Pre-installation steps for Centos
      yum:
        name: "{{ packagesCentos }}"
        update_cache: yes
        state: latest
    # - name: Firewalld
    #   block:
        # - name: Install Firewalld
        #   yum:
        #     name: firewalld
        #     state: present
        # - name: Restart service firewalld
        #   ansible.builtin.service:
        #     name: firewalld
        #     state: started
        #     enabled: yes
        # - name: Add-port=80/tcp
        #   ansible.builtin.shell:
        #     cmd: firewall-cmd --zone=public --add-port=80/tcp --permanent

        # - name: Add-port=2235/tcp
        #   ansible.builtin.shell:
        #     cmd: firewall-cmd --zone=public --add-port=2235/tcp --permanent

        # - name: Add-port=22/tcp
        #   ansible.builtin.shell:
        #     cmd: firewall-cmd --zone=public --add-port=22/tcp --permanent

        # - name: Firewall reload
        #   ansible.builtin.shell:
        #     cmd: firewall-cmd --reload
      # ignore_errors: True

    - name: Pre-installation steps for RedOS
      block:
        - name: Run command for 7.3.2
          ansible.builtin.shell: |
            restorecon -Rv /var/lib/rpm
            rpmdb --rebuilddb

        - name: Remove of pacheges RedOS
          yum:
            name: "{{ packagesRedOS }}"
            state: absent

        - name: Remove of pacheges RedOS
          yum:
            name: "{{ packagesRedOS }}"
            state: absent

        - name: Install app for RedOS7.2
          yum:
            name: "{{ packagesRedOS72 }}"

    
        - name: Remove my.cnf
          ansible.builtin.file:
            path: /etc/my.cnf
            state: absent

        - name: Install dotnet-host
          ansible.builtin.yum:
            name: https://packages.microsoft.com/centos/7/prod/Packages/d/dotnet-host-6.0.9-x64.rpm
            validate_certs: no
            disable_gpg_check: yes

    - name: Run cs install
      ansible.builtin.shell:
        cmd: yes | bash /tmp/install-RedHat.sh
      # register: runscriptcent
      ignore_errors: True