---
- name: test
  hosts: all
  become: true
  tasks:
    - name: Remove all partitions from disk
      command: " parted /dev/sda resizepart 1  Yes 100%"
    - name: Remove all partitions from disk
      command:   "resize2fs /dev/sda1"
