---
- include_tasks: deb.yml
  when:  "'ansible_distribution' == 'Ubuntu' and ('ansible_distribution_version' == '18.04' or 'ansible_distribution_version' == '22.04')"
- include_tasks: deb.yml
  when: ansible_os_family == 'Debian'

- include_tasks: deb.yml
  when: ansible_os_family == 'Astra Linux'

- include_tasks: red.yml
  when: ansible_distribution == 'RED' and ansible_distribution_release == 'MUROM'

- include_tasks: red.yml
  when: (ansible_distribution == "CentOS" ) #and ansible_facts['distribution_major_version'] == "7"