
resource "local_file" "inventory" {
  content = <<-EOT
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    [middle:children]
    cs
    ds
    nginx
    mysql

    [cs]
    cs_1 ansible_host=${openstack_compute_instance_v2.cs_vm.access_ip_v4} ansible_port=2235 ansible_user=root

    [cs_slave]
    #cs_2 ansible_host=

    [ds]
    ds_node ansible_host=${openstack_compute_instance_v2.ds_vm.access_ip_v4} ansible_port=2235 ansible_user=root

    [nginx]
    #lb_node ansible_host=

    [mysql:children]
    master_db
    slave_db

    [master_db]
    master_node ansible_host=${openstack_compute_instance_v2.mm_vm.access_ip_v4} ansible_port=2235 ansible_user=root

    [slave_db]
    slave_node ansible_host=${openstack_compute_instance_v2.ms_vm.access_ip_v4} ansible_port=2235 ansible_user=root
    EOT
  filename = "../inventory/hosts"
  file_permission = "0644"

  depends_on = [
    openstack_compute_instance_v2.cs_vm,
    openstack_compute_instance_v2.ds_vm,
    openstack_compute_instance_v2.mm_vm,
    openstack_compute_instance_v2.ms_vm
  ]
}
