
resource "local_file" "inventory" {
  content = <<-EOT
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [cs]
    cs_1 ansible_host=${openstack_compute_instance_v2.cs_vm.access_ip_v4} ansible_port=${var.ssh_port} ansible_user=root

    [ds]
    ds_node ansible_host=${openstack_compute_instance_v2.ds_vm.access_ip_v4} ansible_port=${var.ssh_port} ansible_user=root

    [nginx]
    #lb_node ansible_host=

    [master_db]
    master_node ansible_host=${openstack_compute_instance_v2.mm_vm.access_ip_v4} ansible_port=${var.ssh_port} ansible_user=root

    [slave_db]
    slave_node ansible_host=${openstack_compute_instance_v2.ms_vm.access_ip_v4} ansible_port=${var.ssh_port} ansible_user=root

    [elc]
    elastic_node ansible_host=${openstack_compute_instance_v2.elc_vm.access_ip_v4}  ansible_port=${var.ssh_port} ansible_user=root
    EOT
  filename = "../inventory/hosts"
  file_permission = "0644"

  depends_on = [
    openstack_compute_instance_v2.cs_vm,
    openstack_compute_instance_v2.ds_vm,
    openstack_compute_instance_v2.mm_vm,
    openstack_compute_instance_v2.ms_vm
  ]
}
