cs: "{{ hostvars[groups['cs'][0]].ansible_host }}" 
ds: "{{ hostvars[groups['ds'][0]].ansible_host }}"  
ms: "{{ hostvars[groups['slave_db'][0]].ansible_host }}" 
mm: "{{ hostvars[groups['master_db'][0]].ansible_host }}"
mysql_root_db_pass: "P@$$w0rd1"
mysql_root_db_user: root
mysql_repl_user:
  - name: repl
    pass: "P@$$w0rd1"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
mysql_cs_repl:
  - name: cs_user
    pass: "Welcome*1"
    priv: "*.*:ALL"
    host: "%"
    db_host: "{{ hostvars[groups['master_db'][0]].ansible_host }}"
DS_password: RrTCPPwQ1wq2
DS_db_psql: r7office
DS_psql_user: r7office
DS_psql_pass: r7office
