--- 
- name: Copy file
  template:
    src: communityserver-configure.sh.j2
    dest: /usr/bin/communityserver-configure.sh
- name: Copy file
  template:
    src: xmppserver-configure.sh.j2
    dest: /usr/bin/xmppserver-configure.sh
- name: SECRET change web.appsettings.config  
  lineinfile:
      path: /usr/bin/communityserver-configure.sh
      regexp: 'DB_HOST="host"' 
      line: 'DB_HOST="{{ mm }}"'
- name: SECRET change web.appsettings.config  
  lineinfile:
      path: /usr/bin/xmppserver-configure.sh
      regexp: 'DB_HOST="host"' 
      line: 'DB_HOST="{{ mm }}"'
- name: run mysql script
  shell: bash /usr/bin/communityserver-configure.sh
- name: run mysql script
  shell: bash /usr/bin/xmppserver-configure.sh