# ---
# - hosts: cs
#   gather_facts: false
#   roles:
#     - cs
# - hosts: ds
#   gather_facts: false
#   roles:
#     - ds
- hosts: master_db
  gather_facts: false
  roles:
    - { role: ms,
              mysql_repl_role: master }
  vars:
    mysql_root_password: "P@$$w0rd1"
- hosts: slave_db
  gather_facts: false
  roles:
    - { role: ms,
              mysql_repl_role: slavedb }



