---
- name: permit port 3306/tcp
  firewalld:
    port: 3306/tcp
    permanent: yes
    zone: public
    state: enabled #present
  ignore_errors: true
- name: install curl
  apt: 
    name: curl
    state: present
- name: Firewall reload
  ansible.builtin.shell:
    cmd: firewall-cmd --reload
  ignore_errors: true
- name: Download rpm rep
  ansible.builtin.shell:
    cmd: curl -o /tmp/mysql-apt-config_0.8.24-1_all.deb -OL http://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb

- name: add key 
  ansible.builtin.apt_key:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql
    state: present
- name: Setting repo
  ansible.builtin.shell:
    cmd: DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/mysql-apt-config_0.8.24-1_all.deb

- name: Rm mysql-apt-config_0.8.24-1_all.deb
  ansible.builtin.shell:
    cmd: rm -f /tmp/mysql-apt-config_0.8.24-1_all.deb



- name: Update repo
  ansible.builtin.apt:
    update_cache: yes


- name: Install mysql
  ansible.builtin.apt:
    name: 
      - mysql-server
      - mysql-client
      - "python3-pymysql"
      - "php-mysql"

- name: started mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
- name: Sets the root password
  mysql_user:
    name: "{{ mysql_root_db_user }}"
    password: "{{ mysql_root_db_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# MASTER
- name: Copy the mysqld.cnf file for Master
  template:
    src: "mysql.cnf_id1"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  notify:
   - restart mysql
  when: mysql_repl_role == 'master'
# SLAVE
- name:  Copy the my.cnf file for Slave
  template:
    src: "mysql.cnf_id2"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  notify:
   - restart mysql
  when: mysql_repl_role == 'slavedb'


- name: Copy .my.cnf file with root password credentials
  template:
    src: "my.cnf.j2"
    dest: "~/.my.cnf"
  notify:
   - restart mysql

- name: Restart systemctl daemon-reload
  command: systemctl daemon-reload
- name: Start the mysql services
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes
